module.exports = {
  ACTIVE: "Active",
  PENDING: "Pending",
  INACTIVE: "Inactive",
  LOCKED: "Locked",
  FUTURE_APPOINTMENT_DAYS_LIMIT: 4,
  APPOINTMENT_MAX_TIME_SLOT_LIMIT: 6,
  SALT_ROUNDS: 10,
  ALREADY_EXISTS: "Email id/phone already exists.",
  ATTEMPT_EXCEEDED: "Attempt exceeded",
  ALREADY_EXISTS_MAPPING: "Mapping already exists",
  INVALID_CREDENTIALS: "Invalid credentials",
  DUPLICATE: "Already exists",
  OTP_SENT: "OTP sent successfully",
  OTP_EXPIRE: 5,
  USER_NOT_FOUND: "User not found",
  NOT_FOUND: "Not found",
  OTP_VERIFIED: "OTP verified successfully",
  INVALID_OTP: "Invalid OTP",
  APPLICANT: "APP",
  OTP_REGISTRATION_SUBJECT: "OTP for verification",
  SUCCESS: "success",
  FORGOT_PASSWORD: "Forgot Password",
  UPDATE_NUMBER: "Update Number",
  PASSWORD_CHANGED: "Password changed successfully",
  PHONE: "phone",
  CALENDER_COLOR_CODES: {
    emergency: "#ff3735",
    declaredHoliday: "#f5a623",
    declareWorkingday: "#b8e986",
  },
  MESSAGE_TEMPLATE_TYPES: {
    REGISTRATION_OTP: "REGISTRATION_OTP",
    LOGIN: "LOGIN",
    FORGOT_PASSWORD: "FORGOT_PASSWORD",
    REGISTRATION_SUCCESS: "REGISTRATION_SUCCESS",
  },
  RESOURCES: {
    TEMP: "TEMP_RESOURCE",
  },
  PERMS: {
    ADD: "ADD",
    EDIT: "EDIT",
    VIEW: "VIEW",
    DELETE: "DELETE",
    EXPORT: "EXPORT",
    PROCESS: "PROCESS",
  },
  DECLARE_HOLIDAY: {
    FULLDAY_PARTIAL_FUTURE: {
      title: `Full day holiday 🛫 on {date} 🗓️ declared ✅`,
      description: `Doctor has declared a full day holiday on {date} 🗓️. Please reschedule your appointment accordingly.`,
    },
    PARTIAL_FUTURE: {
      title: `Your Partial Holiday for session { Session number } 🗓️ has been declared ✅`,
      description: `All appointments on {date} and {session} dismissed with informing patients if any about the dismissal🔕🔚`,
    },
    PARTIAL_TODAY: {
      title: `Your Partial Holiday for session { Session number }🗓️ has been declared ✅`,
      description: `All appointments on {date} and {session} dismissed with informing patients about the dismissal 📴`,
    },
  },
  FULLDAY_TODAY: {
    title: `Your Full Day holiday🚀 for session { session number } has been declared ✅`,
    description: `All appointments on {date} and {session} dismissed with informing patients about the dismissal📵`,
  },
};
